apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: status-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/salvamiguel/gitops-status-demo-config
    targetRevision: strategy/canary
    path: k8s/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: status-prod
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
