apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: status-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/salvamiguel/gitops-status-demo-config
    targetRevision: HEAD
    path: k8s/overlays/staging
  destination:
    server: https://kubernetes.default.svc
    namespace: status-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
