apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-status-demo
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: gitops-status-demo
  template:
    metadata:
      labels:
        app: gitops-status-demo
    spec:
      containers:
        - name: gitops-status-demo
          image: ghcr.io/salvamiguel/gitops-status-demo-app:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: app-config
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 5
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "100m"
              memory: "128Mi"
