apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: gitops-status-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitops-status-demo
  template:
    metadata:
      labels:
        app: gitops-status-demo
    spec:
      containers:
        - name: gitops-status-demo
          image: ghcr.io/salvamiguel/gitops-status-demo-app:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: app-config
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 5
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "100m"
              memory: "128Mi"
  strategy:
    blueGreen:
      activeService: status-demo-active
      previewService: status-demo-preview
      autoPromotionEnabled: false
      scaleDownDelaySeconds: 30
