apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: gitops-status-demo
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: gitops-status-demo
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "100m"
              memory: "128Mi"
